### ISSUE TITLE
can't work in jupyter normally

### ISSUE THREAD

**Issue by zyy515** [BrandonKirbyson/VSCode-Animations#11]
when I open a jupyter file with the plugin,the animation of leftsidebar will be closed.Otherwise,the code completion in jupyter will be disabled or shows unusually(the prompt box isn't under code but far below) if the plugin was launched.

**Comment by BrandonKirbyson** [comment]
The animation of the sidebar doesn't work if it detects an iframe in vscode due to vscode having resizing issues if an animation is applied.

As for the other issue, Could you maybe include a video or image of the issue please.

From what you describe here are a few things to try to help me troubleshoot:

- Run `Animations: Install Animations` which will prompt you to install the custom code again.
- Disable `Smooth Mode`, run `Animations: Open Animation Settings` and find `Smooth Mode` and uncheck it.
- Try disabling `VSCode Animations` extension.

I can fix whatever is the issue, these steps just will help be diagnose what the cause is. Thank you.

**Comment by zyy515** [comment]
***@***.***
Like above the picture shows.The box will shows unusually when I type code in jupyter.
发件人: BrandonKirbyson ***@***.***>
发送时间: 2023年6月11日 22:57
收件人: BrandonKirbyson/VSCode-Animations ***@***.***>
抄送: zyy515 ***@***.***>; Author ***@***.***>
主题: Re: [BrandonKirbyson/VSCode-Animations] can't work in jupyter normally (Issue #11)


The animation of the sidebar doesn't work if it detects an iframe in vscode due to vscode having resizing issues if an animation is applied.

As for the other issue, Could you maybe include a video or image of the issue please.

From what you describe here are a few things to try to help me troubleshoot:

  *   Run Animations: Install Animations which will prompt you to install the custom code again.
  *   Disable Smooth Mode, run Animations: Open Animation Settings and find Smooth Mode and uncheck it.
  *   Try disabling VSCode Animations extension.

I can fix whatever is the issue, these steps just will help be diagnose what the cause is. Thank you.

**Comment by zyy515** [comment]
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/127068653/f5feb57a-979f-4d67-bc7a-9cd6bd41eb7d)
Like above the picture shows.The box will shows unusually when I type code in jupyter.

**Comment by BrandonKirbyson** [comment]
Ok, did you try disabling the extension temporarily?

**Comment by zyy515** [comment]
I'm sorry,I don't understand why should I disable the extension.It seems that I did not describe clearly.I tried disabling the extension and the jupyter in vscode recovered.But when I started it again,all the issues come back.

**Comment by BrandonKirbyson** [comment]
Ok thank you, that's what I needed to know. I fill look into this and let you know soon when I fix it.

**Comment by BrandonKirbyson** [comment]
Did you try disabling `Smooth Mode` yet?

**Comment by zyy515** [comment]
yes,I did.And box still showed unnormally like above

**Comment by BrandonKirbyson** [comment]
Can you check what version the extension is, go to the extension page in vscode and click the arrow next to uninstall and you should see the versions. Make sure it is the most recent version (1.0.9), if not then install most recent (1.0.9).

![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/86384607/3f346834-91c7-4b05-a7ec-a6b2a80713b7)

![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/86384607/07dfbd2b-d4ba-4be6-9221-33eefd4ba200)

**Comment by zyy515** [comment]
My version is 1.0.9
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/127068653/a32881da-2425-48f0-99d5-bf387f0b71d0)

**Comment by BrandonKirbyson** [comment]
Ok, I figured out what the issue is. It has to do with the setting `Animations: Active`, if you set it to `None` it should work. I will publish a fix soon.

**Comment by zyy515** [comment]
Well,that works!Thanks for your patience.

**Comment by BrandonKirbyson** [comment]
Great, the fix is ready and will be published soon. Thank you for helping me debug this.
