### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by wioenena-q** [BrandonKirbyson/VSCode-Animations#13]
Is there Linux support? I tried to use it on Arch Linux but it doesn't work. I tried it on X11 and I tried it on Wayland and the result is negative

OS: Arch Linux
Desktop Environment: Gnome
Wayland Compositor: Hyprland

**Comment by wioenena-q** [comment]
İ fixed

**Comment by xXDeathAbyssXx** [comment]
@wioenena-q how?

**Comment by wioenena-q** [comment]
I implemented the mentioned solutions.
