### ISSUE TITLE
Smooth Mode - Lag when scrolling

### ISSUE THREAD

**Issue by Reyshyram** [BrandonKirbyson/VSCode-Animations#14]
Since I updated, activating smooth mode seems to make my VSCode lag when I scroll.

**Comment by BrandonKirbyson** [comment]
Thank you for making an issue about this. I know what the problem is and it has to do with a complex css selector and I will get to fixing it very soon.

**Comment by BrandonKirbyson** [comment]
This should be fixed with the newest version `1.0.11`.

**Comment by Reyshyram** [comment]
Gonna try that 🙂
