### ISSUE TITLE
File path injected into settings is invalid

### ISSUE THREAD

**Issue by bricebrosig** [BrandonKirbyson/VSCode-Animations#15]
The file path written to the "scode_custom_css.imports" setting appears to be incorrect on windows. It mixes '\\' and '/' (I don't think that is allowed...). It also doesn't begin with "file:///", instead it begins with "file://". According to the custom CSS extension docs, it must begin with file:///.
Furthermore, if i click on the filepath generated by VSCode-Animations, it cannot find the file, if I correct what I describe above, I can open the file just fine.

**Comment by BrandonKirbyson** [comment]
Ok, thank you for making an issue and describing it well. I will fix this and publish the new version soon, until then please just correct it manually.

**Comment by bricebrosig** [comment]
I think I'll just have to wait for the fix. When I reload the window, VSCode-Animations overrides what is manually entered.

This might be a separate issue, but if there are other entries in the "vscode_custom_css.imports" setting, VSCode-Animations will delete all of them and replace it with just the one import it needs.

**Comment by BrandonKirbyson** [comment]
Oh ok, do you mind checking what version of the extension you have?
It should be `1.0.11`, that separate issue was a previous bug but should have been fixed already.
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/86384607/6b9c90b0-f7e7-4b56-98ca-abc9e15fc5eb)

**Comment by bricebrosig** [comment]
I'm on v1.0.11

**Comment by BrandonKirbyson** [comment]
Ok, thanks for checking. I will fix it soon, sorry for the inconvenience.

**Comment by BrandonKirbyson** [comment]
Almost fixed. One last question if you don't mind: when you fix it to start with `file:///` does clicking on the link work or do you also need to correct the slashes?

**Comment by BrandonKirbyson** [comment]
Should be fixed in the new version `1.0.12`. Thanks again for helping fix this.
