### ISSUE TITLE
not working in remote mode

### ISSUE THREAD

**Issue by CaulyKan** [BrandonKirbyson/VSCode-Animations#2]
Environment: vscode 1.78.2 + win10 + wsl2 + VSCode-Animations v1.0.1
How to reproduce:
1. install VSCode-Animations and Custom-CSS-and-JS-loader
2. connect to remote (wsl)
3. VSCode-Animations asks to be installed in remote, while Custom-CSS-and-JS-loader not
4. Animations wont be working whether VSCode-Animations is installed in remote or not.

I think this extension should not be installed in remote, since it's only UI related, just like Custom-CSS-and-JS-loader

**Comment by CaulyKan** [comment]
I belive adding following into package.json will solve the issue: 
```
  "extensionKind": [
    "ui"
  ],
```

**Comment by BrandonKirbyson** [comment]
Ok, should be fixed now. Thank you for finding that.
