### ISSUE TITLE
vscode titlebar sub menu animation issue

### ISSUE THREAD

**Issue by push-on** [BrandonKirbyson/VSCode-Animations#22]
### **Title:** 
Submenu animation starting position issue

### **Description:**
When opening the menu for an application, the submenu starts appearing from the top right corner of the screen instead of starting from the location of the menu item is located or from behind of the menu.

This results in the submenu items being too far from the main sub menu and making it unpleasant for the users.

### **Steps to reproduce:**

- Open vs code with "vscode animations" installed
- Click on the menu icon to open the menu
- Hover over any menu item that has a submenu

Actual: The submenu starts appearing from the top right corner of the screen.

Video demonstrating the issue: [link to video](https://streamable.com/lfpvsa)

**Comment by BrandonKirbyson** [comment]
OK, thanks for making an issue on this and providing great info and a video. I am on a mac so I don't have that menu but it is an easy fix. I will probably publish an updated version a bit later today and let you know when I do.

**Comment by push-on** [comment]
it works. Thanks
