### ISSUE TITLE
Default value of 50 for Focus-Dimming-Amount is not a good idea

### ISSUE THREAD

**Issue by Paladynee** [BrandonKirbyson/VSCode-Animations#24]
After I formatted my computer and had to reinstall all extensions, I noticed my VSCode changing dims when it lost focus. I immadiately noticed and did not like it. Windows usually don't randomly lose dim when you unfocus them.

I just don't think it's a good idea to default to a value of 50 when none of the applications I've ever used in my 10 years of internet and computers incorporated this dimming effect before.

I am not against the dimming effect itself, I am just against the default being such a low value.

**Comment by BrandonKirbyson** [comment]
Ok, I agree with that and maybe I should just disable the effect by default? Probably more people don't want it than do so makes sense to have the default help the majority and people that want it can easily enable it anyways.

**Comment by BrandonKirbyson** [comment]
Disabled by default now and published
