### ISSUE TITLE
Scrolling new item animation content is slightly bigger than the actual content when using "Slide"

### ISSUE THREAD

**Issue by Paladynee** [BrandonKirbyson/VSCode-Animations#25]
During the entire animation of "Slide", the contents of the new item is slightly bigger than the actual content.

Frame by frame inspection:
https://github.com/BrandonKirbyson/VSCode-Animations/assets/62181440/b19d48f0-74ff-4754-ad66-fcdbf4adc052

**Comment by BrandonKirbyson** [comment]
Ok, thanks for the video it helps a lot. I think I know why this is happening and it is because of conflicting animations so I can fix it soon.

**Comment by BrandonKirbyson** [comment]
Fixed and published
