### ISSUE TITLE
Command pallete lags

### ISSUE THREAD

**Issue by xzripper** [BrandonKirbyson/VSCode-Animations#26]
https://github.com/BrandonKirbyson/VSCode-Animations/assets/94743980/3e8c3932-1b1e-4e8b-a327-70e0d284db08

cant leave command pallete after enabling animations

**Comment by BrandonKirbyson** [comment]
Are you on the most recent version?

**Comment by xzripper** [comment]
Yes, its got fixed by disabling command pallete animations, but i wish there was animation.

**Comment by BrandonKirbyson** [comment]
Have you tried reinstalling the extension and running command `Animations: Install Animations`? Sorry but I have no way to produce this myself so I can't debug this properly.
