### ISSUE TITLE
[feature request] animation speed configurable via extension settings

### ISSUE THREAD

**Issue by mbalc** [BrandonKirbyson/VSCode-Animations#27]
I'd love to be able to at the very least adjust the speed of all animations with a single settings number - as I find the default configuration a bit intrusive and distracting, and I think speeding the animations up would make it more bearable for me

**Comment by BrandonKirbyson** [comment]
Ok that's a good idea, thanks for mentioning it. I can probably add this soon.

**Comment by mbalc** [comment]
(actually, the settings from the screenshot did start to work, but I guess only after a reboot or something? now the settings change the speeds immediately after the setting edit)

**Comment by BrandonKirbyson** [comment]
Odd, I will still add a setting for everything together. Should always update instantly, thanks for letting me know about that issue.

**Comment by BrandonKirbyson** [comment]
Published new version with the setting.
