### ISSUE TITLE
vscode became very stuttering

### ISSUE THREAD

**Issue by paeonia-lactiflora** [BrandonKirbyson/VSCode-Animations#30]
I love this animation extension. It works perfectly on my PC. The animation is beautiful. 
I want to install it on the school's public computer, but it makes my vscode very stuttering, so sad.

**Comment by BrandonKirbyson** [comment]
Ok, sorry but there isn't much I can do to fix this, that sounds like css animations not preforming well on that computer. Have you tried disabling a few animations, possibly the cursor effect?

**Comment by paeonia-lactiflora** [comment]
Yes😭, it is indeed a problem with cursor animation. I disabled it and vscode is back to normal again, thank you very much ❤️❤️.
