### ISSUE TITLE
Animations seems to be broken

### ISSUE THREAD

**Issue by stillwu** [BrandonKirbyson/VSCode-Animations#32]
I have updated `vscode` today, and then plugin seems to be broken. I've enabled animations, but it's useless.

It works well before the update, here comes `vscode` info.

```
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by BrandonKirbyson** [comment]
Have you tried running the command `Animations: Install Animations`?
