### ISSUE TITLE
[feature request] use ${userHome} in the next release of apc-extension

### ISSUE THREAD

**Issue by TheAifam5** [BrandonKirbyson/VSCode-Animations#36]
Hey,

I [contributed](https://github.com/drcika/apc-extension/pull/97) a small change to the `apc-extension` which allows use of `${userHome}` in `apc.imports` configuration.

Would you be interested in small adjustment in VSCode-Animations to use `${userHome}` in the future?

Best Regards,
TheAifam5

**Comment by BrandonKirbyson** [comment]
Ok, that's a great idea. I am currently very busy so implementing this couldn't happen for a couple weeks but you are free to make a pr.
