### ISSUE TITLE
Interferes with `resize-quickinput-widget`

### ISSUE THREAD

**Issue by svintit** [BrandonKirbyson/VSCode-Animations#38]
Trying to figure out why this interferes with https://gist.github.com/CaptainVincent/74a15cd9d9c450e961b867f69008ee6e#customize-your-quickinput-widget, and how to possibly have both working. 

Maybe an option to disable the animations for the quick input could solve this? 🤔

**Comment by BrandonKirbyson** [comment]
Ok, what is the issue with the quick input? Is it just not appearing or is some animation messing it up?

**Comment by svintit** [comment]
So strangely, depending on the order of the input list, the first extension always works, but the other does not at all. 

Here is a video showing this:

https://github.com/BrandonKirbyson/VSCode-Animations/assets/44262998/5b7e6f60-2846-4620-a0c2-61db490f331d

**Comment by BrandonKirbyson** [comment]
It seems the fix is to wrap the VSCode Animations path like this:
```json
"apc.imports": [
  "file:///.../resize-quickinput-widget.js",
  {
    "type": "text/javascript",
    "src": "/Users/{user}/.vscode/extensions/brandonkirbyson.vscode-animations-2.0.1/dist/updateHandler.js"
  }
],
```
Let me know if this works. I will implement this in the extension when I get the chance and let you know when the fixed version is published.

**Comment by svintit** [comment]
Oh it does work! Nice find @BrandonKirbyson. Note, it only works with the `"src": "/Users/...." and not `"src": "file::///Users/....".

Thanks for helping out!
