### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by iknownoth1ng** [BrandonKirbyson/VSCode-Animations#39]
# 1. Follow the steps to the end, does not work

# 2. platform:
Version: 1.85.0 (system setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

# 3. gif

![VSCodeAnimations](https://github.com/BrandonKirbyson/VSCode-Animations/assets/54530758/28706929-4072-46ec-bd3f-bc4199eed191)

**Comment by BrandonKirbyson** [comment]
Try using the `Apc Customize UI++` installation method, it works better on Windows. To switch to it, use the command `Animations: Change Install Method` and change it to `Apc Customize UI++`. It will give you notifications that you can then follow to install.
