### ISSUE TITLE
[Bug] Not work in a special vscode remote directory

### ISSUE THREAD

**Issue by GladioFeng** [BrandonKirbyson/VSCode-Animations#43]
As show in the gif picture, vscode-animation do not work in a special remote directory. But it works well in my local MAC mechine
![Jan-07-2024 21-01-03](https://github.com/BrandonKirbyson/VSCode-Animations/assets/100987925/c6afa1a3-3524-42ec-9f94-5fa969bc4608)

**Comment by BrandonKirbyson** [comment]
What install method are you using? `Apc` or `custom css and js`?

**Comment by GladioFeng** [comment]
I try them both, two install method are not work in a special remote directory.

**Comment by BrandonKirbyson** [comment]
It seems that this kind of extension probably can't work in that situation, sorry.
