### ISSUE TITLE
[feature request] Additional css/js importer.

### ISSUE THREAD

**Issue by RoyalFoxy** [BrandonKirbyson/VSCode-Animations#45]
I'm currently using [Vibrancy continued](https://marketplace.visualstudio.com/items?itemName=illixion.vscode-vibrancy-continued) to have a vibrant background. This however doesn't work properly with either of the two css/js loaders available to be used with this extension. Vibrancy continued provides their own with which you can import both css and js files.
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/48829979/4ee13520-5ca5-4c89-abc5-fb4a8ee0f0e5)
It would be cool if you could look into it and check if it's possible to add this as a third option for an installer.

The reason why I don't just use APC for a blurred background boils down to, I couldn't get the titlebar to be transparent and it looked bad :/

Thanks in advance

**Comment by BrandonKirbyson** [comment]
Sorry but unless many many people needed this it complicates the extension too much to be worth it. You could possibly just put that path into the custom css and js imports?

**Comment by BrandonKirbyson** [comment]
If you need help putting in the custom css and js imports or have further questions just reopen the issue, but for now I'll close it.
