### ISSUE TITLE
Can't get to work on new vscode installation

### ISSUE THREAD

**Issue by Zyrus-X** [BrandonKirbyson/VSCode-Animations#48]
Platform: Windows 11

**Tried :** Reinstalling the extension and one-by-one trying both _Custom CSS JS Loader_ and _Apc Customize UI++_ install methods while having one only of them installed and changing to the respective method and enabling animations + reloading.

Help would be appreciated :D

**Comment by BrandonKirbyson** [comment]
Have you tried running `Animations: Install Animations` from the command palette?

**Comment by EririIcy** [comment]
> Did you run as an administrator? That may fix all of your issues.你是以管理员身份运行的吗？这可能会解决你所有的问题。
this really work! thaks a lot
