### ISSUE TITLE
Unable to get Animations to work

### ISSUE THREAD

**Issue by cybercoder-naj** [BrandonKirbyson/VSCode-Animations#49]
Platform: Endeavour OS

After installing the extensions, I also installed "Custom CSS and JS". In my `settings.json`, these are the settings related to the two extensions:

```json
  "vscode_custom_css.imports": [
    "file:///home/nishant/.vscode/extensions/brandonkirbyson.vscode-animations-2.0.1/dist/updateHandler.js"
  ],
  "animations.Enabled": true,
  "animations.CursorAnimation": true
```

I see that `"vscode_custom_css.imports"` links to a javascript file. When I enter `Animations: Open Custom CSS`, I get an empty file. 
None of the animations are working and I'd love some help. Thanks!

**Comment by BrandonKirbyson** [comment]
Have you tried the `Apc` option, using the command `Animations: Change Install Method`. Try that and let me know if that works please. Next step then would be to verify you are running vscode with full permissions.

**Comment by cybercoder-naj** [comment]
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/48282810/1abad598-b320-4b2d-ab9d-70f4de9362d6)

Unfortunately, I am unable to install Apc

**Comment by BrandonKirbyson** [comment]
I think this issue might be the same thing, let me know though. https://github.com/BrandonKirbyson/VSCode-Animations/issues/42
