### ISSUE TITLE
Not working on kali linux

### ISSUE THREAD

**Issue by 3HARSH6** [BrandonKirbyson/VSCode-Animations#52]
VS code animations is not working on kali linux. Don't know why, I tried all troubleshootings.

**Comment by BrandonKirbyson** [comment]
Have you tried using the `Apc` install method. To switch to it, use the command Animations: Change Install Method and change it to Apc Customize UI++. It will give you notifications that you can then follow to install.

And also, if you do a get an error notification, [this issue](https://github.com/BrandonKirbyson/VSCode-Animations/issues/42) may help. It seems to be common on linux, basically you just need to give vscode proper permissions.

**Comment by 3HARSH6** [comment]
Thank you, solution in #49 issue worked.
