### ISSUE TITLE
What is the purpose of the "Tabs" setting?

### ISSUE THREAD

**Issue by NianBroken** [BrandonKirbyson/VSCode-Animations#54]
I have tried to change different values for the "Tabs" setting: None, Scale, Slide, Flip.
But I don't see any change in my VSCODE.

**Comment by NianBroken** [comment]
And I don't know what the "Tabs" setting does either!

**Comment by NianBroken** [comment]
@TheAifam5 @BrandonKirbyson @TobinPalmer

**Comment by BrandonKirbyson** [comment]
It's for when opening new tabs, like this:

<img src="https://raw.githubusercontent.com/BrandonKirbyson/VSCode-Animations/main/static/gifs/Tabs.gif" alt="Tabs" width="300"/>
