### ISSUE TITLE
Custom CSS and JS ？？

### ISSUE THREAD

**Issue by mvpyangxu** [BrandonKirbyson/VSCode-Animations#55]
The plugin has been uninstalled and the icon is still at the bottom ？？

Why does the status bar at the bottom of vscode still have this icon after uninstallation, and there is no response? what can I do to remove this icon that should not exist?
<img width="177" alt="image" src="https://github.com/BrandonKirbyson/VSCode-Animations/assets/54459610/ffcb5ad2-c8cb-4c70-9ff6-ca16287f40aa">

**Comment by BrandonKirbyson** [comment]
I think you have to use the command from the custom css and js extension, `Disable Custom CSS and JS`.

**Comment by mvpyangxu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mvpyangxu** [comment]
Could you explain how to operate it in detail? thank you. ❤️

**Comment by BrandonKirbyson** [comment]
Sorry for not responding, you open up the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and run that command, `Disable Custom CSS and JS`.
