### ISSUE TITLE
Wrong window size quick fix

### ISSUE THREAD

**Issue by Camoukey** [BrandonKirbyson/VSCode-Animations#56]
When the extension is enabled, the quick fix window shrinks to an unreadable size:

![wrong-quick-fix](https://github.com/BrandonKirbyson/VSCode-Animations/assets/58064279/4b4ebf65-26f9-4040-afe7-c92718d822d4)

Once you turn off the animations, the problem disappears:

![normal-quick-fix](https://github.com/BrandonKirbyson/VSCode-Animations/assets/58064279/351e432f-bfbb-43f5-a627-707f265a99b8)

I tried different animation settings for lists, but nothing worked.

**Comment by BrandonKirbyson** [comment]
Ok, thanks for letting me know. I'll take a look at it soon.

**Comment by BrandonKirbyson** [comment]
Fixed in the new version `2.0.2`.
