### ISSUE TITLE
All tab animations not working

### ISSUE THREAD

**Issue by Seng-Jik** [BrandonKirbyson/VSCode-Animations#60]
https://github.com/BrandonKirbyson/VSCode-Animations/assets/11296891/fc35bc89-e06a-4658-aa33-1c8ef9188b23

Starting from a certain version of VSCode, these Tab Animations are no longer available.

**Comment by BrandonKirbyson** [comment]
Wow, sorry, I don't know how I didn't notice this. I'll fix it tomorrow.

**Comment by zixiCat** [comment]
> Wow, sorry, I don't know how I didn't notice this. I'll fix it tomorrow.

seems liike it's not been fixed  yet

**Comment by BrandonKirbyson** [comment]
Oops, published fix now
