### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by Remi-Avec-Un-I** [BrandonKirbyson/VSCode-Animations#61]
Hey, i tryed to install it, and install Apc Customize UI++ using the trouble shooting method you gave, it worked to install it but I don't have any animations playing/working. I tryed to install different versions but nothings seems to works.
I am using fedora
[Capture vidéo du 2024-04-09 22-51-19.webm](https://github.com/BrandonKirbyson/VSCode-Animations/assets/74991151/e9af6af3-0052-4406-a1a9-d3bbdc35c199)

**Comment by BrandonKirbyson** [comment]
Just checking, have you tried running the command `Animations: Install Animations`.

**Comment by Remi-Avec-Un-I** [comment]
Oups my bad it works, thanks you

**Comment by BrandonKirbyson** [comment]
Ok great
