### ISSUE TITLE
GitHub copilot response

### ISSUE THREAD

**Issue by mrgunes** [BrandonKirbyson/VSCode-Animations#62]
when Copilot responses , it blinks for each time responding , is there any way that some extensions out of this animations

**Comment by mrgunes** [comment]
https://github.com/BrandonKirbyson/VSCode-Animations/assets/31079039/b6e0a477-0576-4ef9-82cc-b9e62c6a76fb

**Comment by mrgunes** [comment]
yes , you are right , each response triggers animation , so can you find a way to keep copilot out of this or similar extensions, i believe all AI extensions work the same way

**Comment by SuperManito** [comment]
I second that! I have to set `Scrolling` to `None`.

**Comment by BrandonKirbyson** [comment]
Ok, I think I can remove it. I'll publish a new version with the fix soon.

**Comment by SuperManito** [comment]
> Ok, I think I can remove it. I'll publish a new version with the fix soon.

It should be noted that the AI chat plugin not only has _GitHub Copilot_. Perhaps you should find a suitable method instead of disabling the plugin with the specified name.

**Comment by BrandonKirbyson** [comment]
Published fix in `2.0.3`
