### ISSUE TITLE
How to completely uninstall.

### ISSUE THREAD

**Issue by CaptainVincent** [BrandonKirbyson/VSCode-Animations#64]
For some reason that I don't know, animations always seem to have some latency in my environment. 
(Anyway it's a nice work!)
So... when I tried to remove this extension, 
I could still see 'VSCode-Animations: Successfully Installed!' in the developer tool console.
Has it been completely removed?

**Comment by BrandonKirbyson** [comment]
You have to uninstall either `custom css and js` or `Apc`, whichever you are using. The command should be either `Disable Custom CSS and JS` or `Disable Apc Extension.`

**Comment by CaptainVincent** [comment]
Thank you for your response. 
I just succeeded, but because I am still using APC personally, my steps is

1. To disable APC
2. Uninstall animation, and then enable APC. 

However, I notice that `apc.imports` in preference will not be automatically deleted unused file, so users may need to be reminded to manually remove the import files.
