### ISSUE TITLE
VSCode Animations: Please install Apc Customize UI++ for animations to work

### ISSUE THREAD

**Issue by Akashyc** [BrandonKirbyson/VSCode-Animations#65]
I successfully installed it but it still prompts me
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/39522219/63645dc2-8b53-4c03-816a-3a5d3c8ebac9)

**Comment by BrandonKirbyson** [comment]
What happens if you reload vscode, or click the install button?

**Comment by Akashyc** [comment]
Still show this pop-up window.

**Comment by BrandonKirbyson** [comment]
Ok, could you possibly try reinstalling this extension or try quickly switching the install method to `custom css and js` and back quickly?

**Comment by Akashyc** [comment]
I found the reason, it was caused by a setting in vscode

extensions.experimental.affinity

**Comment by BrandonKirbyson** [comment]
Ok great.
