### ISSUE TITLE
Lag issue when Scrolling

### ISSUE THREAD

**Issue by ViktorTrojan** [BrandonKirbyson/VSCode-Animations#70]
On my PC its not really a Problem but a laptop for example struggles real bad on scrolling.
On Taskmanager it says high gpu usage 10% with rtx 3060ti

Using Vscodium, Windows10

Installed Version:

Apc Customize UI++ v0.3.9
VSCode Animations v2.0.3

The Exported Profile if you want to test:
[VSAnimations_LagProfile.zip](https://github.com/user-attachments/files/16430775/VSAnimations_LagProfile.zip)

**Comment by BrandonKirbyson** [comment]
Sorry for the delay, should be fixed in the new version, `2.0.4`. Let me know if it works please!
