### ISSUE TITLE
Editor laggy when scrolling in smooth mode

### ISSUE THREAD

**Issue by renodesper** [BrandonKirbyson/VSCode-Animations#74]
I've noticed a significant performance drop when scrolling within the editor while "smooth mode" is enabled. The editor becomes noticeably laggy, making it difficult to work efficiently.

I believe this issue is caused by the smooth scrolling effect being applied to the editor, which is not optimized for this type of animation.

Would it be possible to exclude the editor from the smooth mode effect? This would allow for a smoother scrolling experience within the editor while maintaining the overall smooth mode experience in other parts of the application.

**Comment by NgeNXQ** [comment]
The same issue

**Comment by BrandonKirbyson** [comment]
Ok sorry, I'll look into it later. Slight performance issues are expected but sounds like something weird is happening now.

**Comment by BrandonKirbyson** [comment]
Sorry for the delay, should now be fixed in the new version, `2.0.4`. Please let me know if it works or if there are any new issues because I redid the way smooth mode works to make it more efficient.

**Comment by NgeNXQ** [comment]
It might have become better but the stuttering is still there :(
Is it possible to achieve the behavior where the smooth-mode does not affect scrolling in the editors and views at all (but preserving cool animations of hiding/showing editors and sidebars)?
Also, it is kinda counter-intuitive because there are separate preferences in vsc to accomplish these tasks e.g. "editor.smoothScrolling", workbench.list.smoothScrolling" and so on

**Comment by NgeNXQ** [comment]
It would be really nice. Thanks for your time and effort!

**Comment by BrandonKirbyson** [comment]
Could you double check that you updated it please, for me it is perfectly smooth. If it still persists please try `Animations: Install Animations`. If it still is an issue I can try fixing it, just want to check first. Thanks.

**Comment by NgeNXQ** [comment]
Thank you so much! `Animations: Install Animations` did it thing. Thanks for such an awesome extension!

**Comment by BrandonKirbyson** [comment]
Ok great, thanks!
