### ISSUE TITLE
The animations at the workbench stop functioning when the markdown preview is opened

### ISSUE THREAD

**Issue by cnlancehu** [BrandonKirbyson/VSCode-Animations#75]
As the title, the problem occurs on both `Custom CSS and JS` and `Apc Customize UI`

https://github.com/user-attachments/assets/593fa674-1e91-405e-92be-34fa0e82328e

![image](https://github.com/user-attachments/assets/d9413a17-df9e-4bab-9770-907a91ce6496)
with VSCode Animations v2.0.3 and Custom CSS and JS Loader latest

I'm not sure if the issue is with the plugin or something on my end. 
Thank you so much for your amazing plugin

**Comment by BrandonKirbyson** [comment]
That only happens with markdown files right? Unfortunately I had to disable the smooth mode for markdown/html previews because the way vscode works, it wouldn't update the sizing of the preview if animated.

**Comment by cnlancehu** [comment]
Thank you for the quick response. I hadn’t noticed that it’s due to how VSCode handles previews. It’s a bit unfortunate, but I understand the limitation now. I really appreciate all the effort you’ve put into this plugin.
