### ISSUE TITLE
There will be some issues with incomplete coverage

### ISSUE THREAD

**Issue by Strivy-ZSY** [BrandonKirbyson/VSCode-Animations#76]
It's hard to describe in words, please just check out the image.

![1](https://github.com/user-attachments/assets/d736b595-555e-41b2-83a0-a17fe6405ef3)

Thank you so much if you can fix this issue! Love you all 🤓

**Comment by Strivy-ZSY** [comment]
I check GitHub less frequently; if I fail to respond promptly to your message, please accept my apologies.🥺

**Comment by Strivy-ZSY** [comment]
Thank you for solving the issue🤗

**Comment by Strivy-ZSY** [comment]
But I then discovered a new issue the compiler’s animation effect works for a few minutes after installing the plugin but then stops working subsequently🥺This issue didn't exist in older versions

**Comment by BrandonKirbyson** [comment]
Could you clarify what you mean by the compiler's animation effect, are you talking about the terminal in smooth mode?

**Comment by Strivy-ZSY** [comment]
Thanks for your reply!🤗❤️
All animation effects are gone. Not sure if it's a settings issue. Could you please take a look? Thank you so much for your help! 

https://github.com/user-attachments/assets/65c0aa98-ee62-4d96-a96d-26ea4f4d2697

**Comment by BrandonKirbyson** [comment]
@Strivy-ZSY Ok, currently `Apc Customize UI++` is not working so please try changing the install method to `Custom CSS and JS` and then run `Animations: Install Animations`. If that doesn't work please follow [this issue](https://github.com/BrandonKirbyson/VSCode-Animations/issues/78).

**Comment by Strivy-ZSY** [comment]
Alright now we have the animation thanks for your patience! ❤️
But VSCode popped up a warning saying "Code installation seems damaged. Please reinstall". It's likely due to an issue with custom CSS import locally but shouldn't affect usage.
Overall the issue has been resolved! thank you!🤗❤️

**Comment by BrandonKirbyson** [comment]
Ok great! The popup is always there with custom plugins, just click the gear and "Do Not Show Again".
