### ISSUE TITLE
a bug for vscode-animations

### ISSUE THREAD

**Issue by NatholDallas** [BrandonKirbyson/VSCode-Animations#9]
When i enable this plugin , i using live share to view my html , but he have a problem, i try to fix, but such as these Render preview of the plugin, he have own label in vscode html, so he not have animation, and he will make some problem, just like this
![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/109703293/f5de593f-83df-4a11-98fb-a2f540f6a4b4)
so is a big problem......
Because if you want to fix it, you can only do compatibility with related plugins

**Comment by BrandonKirbyson** [comment]
I actually have a somewhat solution that I need to publish. It temp disables smooth mode with previews because vscode has manual resizing and it conflicts with transitions. I will publish fixed version later today.

**Comment by BrandonKirbyson** [comment]
Published 1.0.8 which fixes this issue.

**Comment by oamaxa** [comment]
Scroll animations don't work on 1.0.8
